services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://localhost:8080
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    env_file:
      - .env
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    restart: always
    environment:
      - DB_URL=postgresql://${USER}:${PASSWORD}@postgres:${DB_PORT}/${DB_NAME}
    depends_on:
      - database
    env_file:
      - .env
  database:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
  # db_test:
  #   build: ./server
  #   command: pytest
  #   volumes:
  #     - ./server:/app
  #   depends_on:
  #     - database
