"""Expand book model

Revision ID: 7c88e01148d7
Revises: 7916d2d6d192
Create Date: 2025-05-27 15:29:20.145969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c88e01148d7'
down_revision: Union[str, None] = '7916d2d6d192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('purchase_method', sa.Enum('library', 'gifted', 'bought', name='purchasemethod'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'purchase_method')
    # ### end Alembic commands ###
